port: 7890

redir-port: 7892

mixed-port: 7893

# Linux å’Œ macOS çš„ redir ä»£ç†ç«¯å£ (å¦‚éœ€ä½¿ç”¨æ­¤åŠŸèƒ½ï¼Œè¯·å–æ¶ˆæ³¨é‡Š)
# redir-port: 7892

# å…è®¸å±€åŸŸç½‘çš„è¿æ¥ï¼ˆå¯ç”¨æ¥å…±äº«ä»£ç†ï¼‰
allow-lan: true

# ä»…åœ¨å°†allow-lanè®¾ç½®ä¸ºtrueæ—¶é€‚ç”¨
# #"*": ç»‘å®šæ‰€æœ‰IPåœ°å€
# #192.168.122.11: ç»‘å®šå•ä¸ªIPv4åœ°å€
# #"[aaaa::a8aa:ff:fe09:57d8]": ç»‘å®šå•ä¸ªIPv6åœ°å€
bind-address: "*"
ipv6: false

# è§„åˆ™æ¨¡å¼ï¼šruleï¼ˆè§„åˆ™ï¼‰ / globalï¼ˆå…¨å±€ä»£ç†ï¼‰/ directï¼ˆå…¨å±€ç›´è¿ï¼‰/ script (è„šæœ¬)
mode: rule

# è®¾ç½®æ—¥å¿—è¾“å‡ºçº§åˆ« (é»˜è®¤çº§åˆ«ï¼šsilentï¼Œå³ä¸è¾“å‡ºä»»ä½•å†…å®¹ï¼Œä»¥é¿å…å› æ—¥å¿—å†…å®¹è¿‡å¤§è€Œå¯¼è‡´ç¨‹åºå†…å­˜æº¢å‡ºï¼‰ã€‚
# 5 ä¸ªçº§åˆ«ï¼šsilent / error / warning / info / debugã€‚çº§åˆ«è¶Šé«˜æ—¥å¿—è¾“å‡ºé‡è¶Šå¤§ï¼Œè¶Šå€¾å‘äºè°ƒè¯•ï¼Œè‹¥éœ€è¦è¯·è‡ªè¡Œå¼€å¯ã€‚
log-level: debug

# Clash çš„ RESTful API
external-controller: '127.0.0.1:9090'

hosts:
  # Firebase Cloud Messaging
  'mtalk.google.com': 108.177.125.188
  # Google Dl
  'dl.google.com': 180.163.151.161
  'dl.l.google.com': 180.163.151.161

dns:
  enable: true # æ˜¯å¦å¯ç”¨dns false
#  enhanced-mode: redir-host # æ¨¡å¼ï¼šredir-hostæˆ–fake-ip
  listen: 0.0.0.0:7874 #
  #fake-ip-filter: # fake ip ç™½åå•åˆ—è¡¨ï¼Œå¦‚æœä½ ä¸çŸ¥é“è¿™ä¸ªå‚æ•°çš„ä½œç”¨ï¼Œè¯·å‹¿ä¿®æ”¹
     #- '*.lan'
     #- localhost.ptlogin2.qq.com
  nameserver:
    - 114.114.114.114
    - 223.6.6.6
    - 119.29.29.29
  fallback:
    - https://dns.cloudflare.com/dns-query
    - tls://dot.tiar.app
  fallback-filter:
    geoip: true
    geoip-code: CN
    domain:
      - '+.google.+'
      - '+.googleapis.com'
      - '+.googlevideo.com'
      - '+.gstatic.cn'
      - '+.gstatic.com'
      - '+.gvt1.com'
      - '+.gvt2.com'
      - '+.recaptcha.net'
      - '+.twimg.com'
      - '+.twitter.com'
      - '+.youtube.com'
      - '+.ytimg.com'
      - 'twitter.com'
      - 't.co'
      - 't.me'
      - 'telegra.ph'
      - 'youtu.be'
  # Lookup domains via specific nameservers
  nameserver-policy:
    # Alibaba
    '*.alibaba.cn': '223.6.6.6'
    '*.alibaba.com.cn': '223.6.6.6'
    '*.china.alibaba.com': '223.6.6.6'
    '*.1688.com': '223.6.6.6'
    '*.taobao.com': '223.6.6.6'
    '*.tbcache.com': '223.6.6.6'
    '*.tmall.com': '223.6.6.6'
    '*.alicdn.com': '223.6.6.6'
    '*.aliyundrive.com': '223.6.6.6'
    '*.aliyun.*': '223.6.6.6'
    '*.aliyuncdn.*': '223.6.6.6'
    '*.aliyuncs.com': '223.6.6.6'
    '*.aliyundunwaf.com': '223.6.6.6'
    '*.aliapp.com': '223.6.6.6'
    '*.aliapp.org': '223.6.6.6'
    '*.alibabausercontent.com': '223.6.6.6'
    '*.mmstat.com': '223.6.6.6'
    'tb.cn': '223.6.6.6'

# Clash for Windows
# Proxies module latency test settings
cfw-latency-timeout: 3000
cfw-latency-url: http://www.gstatic.com/generate_204


#è‡ªå®šä¹‰é…ç½®ç›®å½•
#cfw-profiles-path: 'C:\Users\Administrator\.config\clash\profiles'

# æ‰“æ–­è¿æ¥
# Identify strategy of breaking connections after switching to a new proxy/profile/mode
# Options for proxy: none, chain(proxy group in connection chains), all
# Options for profile: true, false
# Options for mode: true, false
cfw-conn-break-strategy:
  proxy: chain # none/chain/all
  profile: true # true/false
  mode: true # true/false

cfw-proxies-order: default



proxies:

# æœåŠ¡å™¨èŠ‚ç‚¹è®¢é˜…
proxy-providers:

  HK:
    type: http
    path: ./Provider/Proxy/Sub/HK.yaml
    url: https://james82.ga/getprofile?name=profiles/JamesConfig.ini&token=Jiange..
    interval: 3600
    filter: 'æ¸¯|HK|Hong Kong|Macau'
    health-check: 
      enable: true
      url: http://www.gstatic.com/generate_204
      interval: 600
  TW:
    type: http
    path: ./Provider/Proxy/Sub/TW.yaml
    url: https://james82.ga/getprofile?name=profiles/JamesConfig.ini&token=Jiange..
    interval: 3600
    filter: 'å°|æ–°åŒ—|å½°åŒ–|TW|Taiwan'
    health-check: 
      enable: true
      url: http://www.gstatic.com/generate_204
      interval: 600
  US:
    type: http
    path: ./Provider/Proxy/Sub/US.yaml
    url: https://james82.ga/getprofile?name=profiles/JamesConfig.ini&token=Jiange..
    interval: 3600
    filter: 'ç¾|æ³¢ç‰¹å…°|è¾¾æ‹‰æ–¯|ä¿„å‹’å†ˆ|å‡¤å‡°åŸ|è´¹åˆ©è’™|ç¡…è°·|æ‹‰æ–¯ç»´åŠ æ–¯|æ´›æ‰çŸ¶|åœ£ä½•å¡|åœ£å…‹æ‹‰æ‹‰|è¥¿é›…å›¾|èŠåŠ å“¥|US|United States'
    health-check: 
      enable: true
      url: http://www.gstatic.com/generate_204
      interval: 600
  JP:
    type: http
    path: ./Provider/Proxy/Sub/JP.yaml
    url: https://james82.ga/getprofile?name=profiles/JamesConfig.ini&token=Jiange..
    interval: 3600
    filter: 'æ—¥æœ¬|JP|Japan'
    health-check: 
      enable: true
      url: http://www.gstatic.com/generate_204
      interval: 600
  KR:
    type: http
    path: ./Provider/Proxy/Sub/SG.yaml
    url: https://james82.ga/getprofile?name=profiles/JamesConfig.ini&token=Jiange..
    interval: 3600
    filter: 'KR|Korea|KOR|é¦–å°”|éŸ©|éŸ“'
    health-check: 
      enable: true
      url: http://www.gstatic.com/generate_204
      interval: 600
      
   
  SA:
    type: http
    path: ./Provider/Proxy/Sub/SA.yaml
    url: https://james82.ga/getprofile?name=profiles/JamesConfig.ini&token=Jiange..
    interval: 3600
    filter: 'Mexico|Argentina|Chile|Costa Rica|é˜¿æ ¹å»·|å·´è¥¿|æ™ºåˆ©|Philippines|India|Turkey|Egypt|è²å¾‹å®¾|å°åº¦|åœŸè€³å…¶|å¾·å›½|åŸƒåŠ|Germany|Bulgaria|Spain|Netherlands|United Kingdom|ä¿åŠ åˆ©äºš|è¥¿ç­ç‰™|è·å…°|è‹±å›½a'
    health-check: 
      enable: true
      url: http://www.gstatic.com/generate_204
      interval: 600
  TR:
    type: http
    path: ./Provider/Proxy/Sub/TR.yaml
    url: https://james82.ga/getprofile?name=profiles/JamesConfig.ini&token=Jiange..
    interval: 3600
    filter: 'åœŸè€³å…¶|TR|Turkey'
    health-check: 
      enable: true
      url: http://www.gstatic.com/generate_204
      interval: 600
  
  UN:
    type: http
    path: ./Provider/Proxy/Sub/UN.yaml
    url: https://james82.ga/getprofile?name=profiles/JamesConfig.ini&token=Jiange..
    interval: 3600
    health-check: 
      enable: true
      url: http://www.gstatic.com/generate_204
      interval: 600

proxy-groups:
  - name: "ğŸš€ Proxy"
    type: select
    proxies:
      - âœˆï¸ Server
      - ğŸ‡¨ğŸ‡³ TW
      - ğŸ‡ºğŸ‡² US
      - ğŸ‡­ğŸ‡° HK
      - ğŸ‡¯ğŸ‡µ JP
      - ğŸ‡¸ğŸ‡¬ SG
      - ğŸ‡°ğŸ‡· KR
      
  - name: "âœˆï¸ Server"
    type: select
    use:
      - UN
      
  - name: "ğŸ“¹ Youtube"
    type: select
    proxies:
      - ğŸ‡ºğŸ‡² US
      - ğŸš€ Proxy
      - ğŸ‡¸ğŸ‡¬ SG
      - ğŸ‡¨ğŸ‡³ TW
      
  - name: "ğŸ¥ Netflix"
    type: select
    proxies:
      - ğŸ‡¨ğŸ‡³ TW
      - ğŸ‡¸ğŸ‡¬ SG
      - ğŸ‡¯ğŸ‡µ JP
      - ğŸ‡­ğŸ‡° HK
      - ğŸ‡ºğŸ‡² US
      - ğŸ‡°ğŸ‡· KR
      - âœˆï¸ Server
      
  - name: "ğŸ“² Telegram"
    type: select
    proxies:
      - ğŸ‡­ğŸ‡° HK
      - ğŸ‡¨ğŸ‡³ TW
      - ğŸ‡¯ğŸ‡µ JP
      
  - name: "ğŸ“º PrimeVideo"
    type: select
    proxies:
      - ğŸ‡¨ğŸ‡³ TW
      - ğŸ‡ºğŸ‡² US
      - â„ï¸ Rare
      
  - name: "ğŸ€ StarPlus"
    type: select
    use:
      - SA
      
  - name: "ğŸ‡¨ğŸ‡³ TW"
    type: select
    use:
      - TW
      
  - name: "ğŸ‡ºğŸ‡² US"
    type: select
    use:
      - US
      
  - name: "ğŸ‡­ğŸ‡° HK"
    type: select
    use:
      - HK
      
  - name: "ğŸ‡¯ğŸ‡µ JP"
    type: select
    use:
      - JP

  - name: "ğŸ‡¸ğŸ‡¬ SG"
    type: select
    use:
      - SG
      
  - name: "ğŸ‡°ğŸ‡· KR"
    type: select
    use:
      - KR
      
  - name: "â„ï¸ Rare"
    type: select
    use:
      - SA
      
  - name: "ğŸ“¢ FCM"
    type: select
    proxies:
      - ğŸ‡­ğŸ‡° HK
      - ğŸ‡¨ğŸ‡³ TW
      - DIRECT
      
  - name: "ğŸŒ GlobalMedia"
    type: select
    proxies:
      - ğŸ‡­ğŸ‡° HK
      - ğŸ‡¨ğŸ‡³ TW
      - ğŸ‡¸ğŸ‡¬ SG
      - ğŸ‡¯ğŸ‡µ JP
      - ğŸ‡ºğŸ‡² US
      - ğŸ‡°ğŸ‡· KR
      - âœˆï¸ Server
      
  - name: "ğŸ“º BiliBili"
    type: select
    proxies:
      - ğŸ¯ Direct
      - ğŸ‡¨ğŸ‡³ TW
      - ğŸ‡­ğŸ‡° HK

  - name: "ğŸŸ Other"
    type: select
    proxies:
      - ğŸš€ Proxy
      - DIRECT
      - ğŸ‡­ğŸ‡° HK
      - ğŸ‡¨ğŸ‡³ TW
      - ğŸ‡ºğŸ‡² US
      - ğŸ‡¸ğŸ‡¬ SG
      - ğŸ‡°ğŸ‡· KR
      
  - name: "â“‚ï¸ Microsoft"
    type: select
    proxies:
      - DIRECT
      - ğŸš€ Proxy
      - ğŸ‡ºğŸ‡² US
      - ğŸ‡­ğŸ‡° HK
      
  - name: "ğŸ Apple"
    type: select
    proxies:
      - DIRECT
      - ğŸš€ Proxy
      - ğŸ‡ºğŸ‡² US
      - ğŸ‡­ğŸ‡° HK
      - ğŸ‡¨ğŸ‡³ TW
      - ğŸ‡¯ğŸ‡µ JP
      
  - name: "ğŸ® Game"
    type: select
    proxies:
      - DIRECT
      - ğŸš€ Proxy
      - ğŸ‡ºğŸ‡² US
      - ğŸ‡­ğŸ‡° HK
      
  - name: "ğŸ¯ Direct"
    type: select
    proxies:
      - DIRECT
      - ğŸš€ Proxy
      
  - name: "ğŸ›‘ Reject"
    type: select
    proxies:
      - REJECT
      - DIRECT

# å…³äº Rule Provider è¯·æŸ¥é˜…ï¼šhttps://lancellc.gitbook.io/clash/clash-config-file/rule-provider

rule-providers:
# name: # Provider åç§°
#   type: http # http æˆ– file
#   behavior: classical # æˆ– ipcidrã€  - DOMAIN
#   path: # æ–‡ä»¶è·¯å¾„
#   url: # åªæœ‰å½“ç±»å‹ä¸º HTTP æ—¶æ‰å¯ç”¨ï¼Œæ‚¨ä¸éœ€è¦åœ¨æœ¬åœ°ç©ºé—´ä¸­åˆ›å»ºæ–°æ–‡ä»¶ã€‚
#   interval: # è‡ªåŠ¨æ›´æ–°é—´éš”ï¼Œä»…åœ¨ç±»å‹ä¸º HTTP æ—¶å¯ç”¨

  LocalAreaNetwork:
    type: http
    behavior: classical
    path: ./Provider/LocalAreaNetwork.yaml
    url: https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Providers/LocalAreaNetwork.yaml
    interval: 86400

  UnBan:
    type: http
    behavior: classical
    path: ./Provider/UnBan.yaml
    url: https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Providers/UnBan.yaml
    interval: 86400
    
  Pikpak:
    type: http
    behavior: classical
    path: ./Provider/RuleSet/Pikpak.yaml
    url: https://raw.githubusercontent.com/JamesLiu0802/JamesConf/main/Clash/Providers/Pikpak.yaml
    interval: 86400
    

  EmbyDirect:
    type: http
    behavior: classical
    path: ./Provider/RuleSet/EmbyDirect.yaml
    url: https://raw.githubusercontent.com/JamesLiu0802/JamesConf/main/Clash/Providers/EmbyDirect.yaml
    interval: 86400
    
  BanAD:
    type: http
    behavior: classical
    path: ./Provider/RuleSet/Guard/BanAD.yaml
    url: https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Providers/BanAD.yaml
    interval: 86400

  BanProgramAD:
    type: http
    behavior: classical
    path: ./Provider/RuleSet/Guard/BanProgramAD.yaml
    url: https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Providers/BanProgramAD.yaml
    interval: 86400

  PrimeVideo:
    type: http
    behavior: classical
    path: ./Provider/RuleSet/PrimeVideo.yaml
    url: https://raw.githubusercontent.com/HotKids/Rules/master/Clash/RuleSet/Prime%20Video.yaml
    interval: 86400

  GoogleFCM:
    type: http
    behavior: classical
    path: ./Provider/RuleSet/GoogleFCM.yaml
    url: https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Providers/Ruleset/GoogleFCM.yaml
    interval: 86400

  GoogleCN:
    type: http
    behavior: classical
    path: ./Provider/RuleSet/GoogleCN.yaml
    url: https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Providers/Ruleset/GoogleCN.yaml
    interval: 86400

  SteamCN:
    type: http
    behavior: classical
    path: ./Provider/RuleSet/SteamCN.yaml
    url: https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Providers/Ruleset/SteamCN.yaml
    interval: 86400

  OneDrive:
    type: http
    behavior: classical
    path: ./Provider/RuleSet/OneDrive.yaml
    url: https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Providers/Ruleset/OneDrive.yaml
    interval: 86400

  Microsoft:
    type: http
    behavior: classical
    path: ./Provider/RuleSet/Microsoft.yaml
    url: https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Providers/Ruleset/Microsoft.yaml
    interval: 86400

  Apple:
    type: http
    behavior: classical
    path: ./Provider/Ruleset/Apple.yaml
    url: https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Providers/Ruleset/Apple.yaml
    interval: 86400
    
  Telegram:
    type: http
    behavior: classical
    path: ./Provider/RuleSet/Telegram.yaml
    url: https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Providers/Ruleset/Telegram.yaml
    interval: 86400

  Epic:
    type: http
    behavior: classical
    path: ./Provider/RuleSet/Epic.yaml
    url: https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Providers/Ruleset/Epic.yaml
    interval: 86400

  Sony:
    type: http
    behavior: classical
    path: ./Provider/RuleSet/Sony.yaml
    url: https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Providers/Ruleset/Sony.yaml
    interval: 86400

  Steam:
    type: http
    behavior: classical
    path: ./Provider/RuleSet/Steam.yaml
    url: https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Providers/Ruleset/Steam.yaml
    interval: 86400

  Youtube:
    type: http
    behavior: classical
    path: ./Provider/RuleSet/Youtube.yaml
    url: https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Providers/Ruleset/Youtube.yaml
    interval: 86400
    
  Emby:
    type: http
    behavior: classical
    path: ./Provider/RuleSet/Emby.yaml
    url: https://raw.githubusercontent.com/JamesLiu0802/ACL4SSR/master/Clash/Providers/Ruleset/Emby.yaml
    interval: 86400
    
  StreamingTW:
    type: http
    behavior: classical
    path: ./Provider/RuleSet/StreamingTW.yaml
    url: https://raw.githubusercontent.com/JamesLiu0802/JamesConf/main/Clash/Providers/Streaming_TW.yaml
    interval: 86400

  HBOGO:
    type: http
    behavior: classical
    path: ./Provider/RuleSet/HBOGO.yaml
    url: https://raw.githubusercontent.com/HotKids/Rules/master/Clash/RuleSet/HBO_Go.yaml
    interval: 86400

  Line:
    type: http
    behavior: classical
    path: ./Provider/RuleSet/Line.yaml
    url: https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/Line/Line.yaml
    interval: 86400

  Facebook:
    type: http
    behavior: classical
    path: ./Provider/RuleSet/Facebook.yaml
    url: https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/Facebook/Facebook.yaml
    interval: 86400

  StreamingJP:
    type: http
    behavior: classical
    path: ./Provider/RuleSet/StreamingJP.yaml
    url: https://raw.githubusercontent.com/JamesLiu0802/JamesConf/main/Clash/Providers/Streaming_JP.yaml
    interval: 86400
    
  StreamingUS:
    type: http
    behavior: classical
    path: ./Provider/RuleSet/StreamingUS.yaml
    url: https://raw.githubusercontent.com/JamesLiu0802/JamesConf/main/Clash/Providers/Streaming_US.yaml
    interval: 86400
    
    
#  LeaguePass:
#    type: http
#    behavior: classical
#    path: ./Provider/RuleSet/LeaguePass.yaml
#    url: https://raw.githubusercontent.com/JamesLiu0802/ACL4SSR/master/Clash/Providers/Ruleset/NBA.yaml
#    interval: 86400   
    
  StarPlus:
    type: http
    behavior: classical
    path: ./Provider/RuleSet/StarPlus.yaml
    url: https://raw.githubusercontent.com/JamesLiu0802/JamesConf/main/Clash/Providers/StarPlus.yaml
    interval: 86400

  Porn:
    type: http
    behavior: classical
    path: ./Provider/RuleSet/Porn.yaml
    url: https://raw.githubusercontent.com/JamesLiu0802/JamesConf/main/Clash/Providers/Porn.yaml
    interval: 86400

  Pornhub:
    type: http
    behavior: classical
    path: ./Provider/RuleSet/Pornhub.yaml
    url: https://raw.githubusercontent.com/JamesLiu0802/JamesConf/main/Clash/Providers/Pornhub.yaml
    interval: 86400

  DisneyPlus:
    type: http
    behavior: classical
    path: ./Provider/RuleSet/DisneyPlus.yaml
    url: https://raw.githubusercontent.com/JamesLiu0802/JamesConf/main/Clash/Providers/DisneyPlus.yaml
    interval: 86400

  Netflix:
    type: http
    behavior: classical
    path: ./Provider/RuleSet/Netflix.yaml
    url: https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Providers/Ruleset/Netflix.yaml
    interval: 86400
 
  BilibiliHMT:
    type: http
    behavior: classical
    path: ./Provider/RuleSet/BilibiliHMT.yaml
    url: https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Providers/Ruleset/BilibiliHMT.yaml
    interval: 86400
    
  Bilibili:
    type: http
    behavior: classical
    path: ./Provider/RuleSet/Bilibili.yaml
    url: https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Providers/Ruleset/Bilibili.yaml
    interval: 86400
    
  ChinaMedia:
    type: http
    behavior: classical
    path: ./Provider/ChinaMedia.yaml
    url: https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Providers/ChinaMedia.yaml
    interval: 86400
    
  ProxyMedia:
    type: http
    behavior: classical
    path: ./Provider/ProxyMedia.yaml
    url: https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Providers/ProxyMedia.yaml
    interval: 86400
    
  HK:
    type: http
    behavior: classical
    path: ./Provider/Ruleset/HK.yaml
    url: https://raw.githubusercontent.com/JamesLiu0802/JamesConf/main/Clash/Providers/HK.yaml
    interval: 86400

  Whatsapp:
    type: http
    behavior: classical
    path: ./Provider/Ruleset/Whatsapp.yaml
    url: https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/Whatsapp/Whatsapp.yaml
    interval: 86400
    
  TW:
    type: http
    behavior: classical
    path: ./Provider/Ruleset/TW.yaml
    url: https://raw.githubusercontent.com/JamesLiu0802/JamesConf/main/Clash/Providers/TW.yaml
    interval: 86400
    
  US:
    type: http
    behavior: classical
    path: ./Provider/Ruleset/US.yaml
    url: https://raw.githubusercontent.com/JamesLiu0802/JamesConf/main/Clash/Providers/US.yaml
    interval: 86400
    
  ProxyGFWlist:
    type: http
    behavior: classical
    path: ./Provider/ProxyGFWlist.yaml
    url: https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Providers/ProxyGFWlist.yaml
    interval: 86400
    
  ChinaDOMAIN:
    type: http
    behavior: classical
    path: ./Provider/ChinaDOMAIN.yaml
    url: https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Providers/ChinaDOMAIN.yaml
    interval: 86400
    
  ChinaCompanyIp:
    type: http
    behavior: ipcidr
    path: ./Provider/ChinaCompanyIp.yaml
    url: https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Providers/ChinaCompanyIp.yaml
    interval: 86400
    
  Download:
    type: http
    behavior: classical
    path: ./Provider/Download.yaml
    url: https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Providers/Download.yaml
    interval: 86400
    

# è§„åˆ™
rules:
  # Unbreak
  - RULE-SET,LocalAreaNetwork,ğŸ¯ Direct
  - RULE-SET,UnBan,ğŸ¯ Direct
  - RULE-SET,Pikpak,ğŸš€ Proxy
  - RULE-SET,EmbyDirect,ğŸ¯ Direct

  # AdBlock
  - RULE-SET,BanAD,ğŸ›‘ Reject
  - RULE-SET,BanProgramAD,ğŸ›‘ Reject
  
  # FCM
  - RULE-SET,GoogleFCM,ğŸ“¢ FCM
  - RULE-SET,GoogleCN,ğŸ¯ Direct

  - RULE-SET,SteamCN,ğŸ¯ Direct
  
  #Microsoft & Apple
  - RULE-SET,OneDrive,â“‚ï¸ Microsoft
  - RULE-SET,Microsoft,â“‚ï¸ Microsoft
  - RULE-SET,Apple,ğŸ Apple
  
  # Telegram
  - RULE-SET,Telegram,ğŸ“² Telegram

  # Game
  - RULE-SET,Epic,ğŸ® Game
  - RULE-SET,Sony,ğŸ® Game
  - RULE-SET,Steam,ğŸ® Game

  # Streaming
  - RULE-SET,Youtube,ğŸ“¹ Youtube
  - RULE-SET,Emby,ğŸ‡ºğŸ‡² US
#  - RULE-SET,LeaguePass,LeaguePass
  - RULE-SET,PrimeVideo,ğŸ“º PrimeVideo
  - RULE-SET,StreamingTW,ğŸ‡¨ğŸ‡³ TW
  - RULE-SET,HBOGO,ğŸ‡¨ğŸ‡³ TW
  - RULE-SET,Line,ğŸ‡¨ğŸ‡³ TW
  - RULE-SET,Facebook,ğŸ‡¨ğŸ‡³ TW
  - RULE-SET,StreamingJP,ğŸ‡¯ğŸ‡µ JP
  - RULE-SET,StreamingUS,ğŸ‡ºğŸ‡² US
  - RULE-SET,StarPlus,ğŸ€ StarPlus
  - RULE-SET,Porn,ğŸ‡ºğŸ‡² US
  - RULE-SET,Pornhub,ğŸ‡ºğŸ‡² US
  - RULE-SET,DisneyPlus,ğŸ¥ Netflix
  - RULE-SET,Netflix,ğŸ¥ Netflix
  - RULE-SET,BilibiliHMT,ğŸ“º BiliBili
  - RULE-SET,Bilibili,ğŸ“º BiliBili
  
  - RULE-SET,ChinaMedia,ğŸ¯ Direct
  - RULE-SET,ProxyMedia,ğŸŒ GlobalMedia
  - RULE-SET,US,ğŸ‡ºğŸ‡² US
  - RULE-SET,TW,ğŸ‡¨ğŸ‡³ TW
  - RULE-SET,Whatsapp,ğŸ‡­ğŸ‡° HK
  - RULE-SET,ProxyGFWlist,ğŸš€ Proxy
  - RULE-SET,HK,ğŸ‡­ğŸ‡° HK
  - RULE-SET,ChinaDOMAIN,ğŸ¯ Direct
  - RULE-SET,ChinaCompanyIp,ğŸ¯ Direct
  - RULE-SET,Download,ğŸ¯ Direct
  - GEOIP,CN,ğŸ¯ Direct

  - MATCH,ğŸŸ Other
